[package]
name = "main"
version = "0.1.0"
authors = ["Mikael Modin <mikael@badsynthesis.com>"]
edition = "2018"

[dependencies]
duttcrypt = { path = "../duttcrypt" }
aes = "0.3.2"
sha-1 = "0.8.1"
rand = "0.7"
